### ISSUE TITLE
稀にMisskeyの通知音が鳴らない時がある

### ISSUE THREAD

**Issue by mujin-nohuman** [Kur0den/Kur0den#13]
もしかしたらおま環かもしれませんが新しいノートや通知が来てるのに音が鳴らない事があります
バグなのか仕様なのかわからないので教えていただけると幸いです。

**Comment by WinLinux1028** [comment]
Go to https://github.com/misskey-dev/misskey/issues

**Comment by natumi-kaoru** [comment]
PCの音量を1億にしてください

**Comment by makaseloli** [comment]
通知音を脳内で鳴らせば解決です
