### ISSUE TITLE
働く気力がない

### ISSUE THREAD

**Issue by Kur0den** [Kur0den/Kur0den#2]
これはバグでしょうか?

**Comment by Kur0den** [comment]
よく考えたら仕様だったためcloseします。

**Comment by 1673beta** [comment]
バグではないでしょうか。

**Comment by Kur0den** [comment]
> バグではないでしょうか。

調べて見たところ労働意欲パッチに未対応のバージョンのようです

**Comment by natumi-kaoru** [comment]
クラス「Government」に関数「force_labour」を実装すれば労働が実装できます
